<?php
namespace Eris;

use Eris\Generator\GeneratedValue;
use Eris\Generator\GeneratedValueSingle;

/**
 * Generic interface for a type <T>.
 *
 * T is covariant: a Generator<int<0, max>> can be used where a
 * Generator<int> is expected, and oneOf(), frequency(), tuple() and
 * associative() can combine Generators of different types.
 *
 * @template-covariant T
 */
interface Generator
{
    /**
     * @param int $size The generation size
     * @return GeneratedValueSingle<T>
     */
    public function __invoke($size, Random\RandomRange $rand);

    /**
     * The conditions for terminating are either:
     * - returning the same GeneratedValueSingle passed in
     * - returning an empty GeneratedValueOptions
     *
     * $element is a value previously generated by this Generator.
     * It is declared as GeneratedValue<mixed> because a covariant
     * template type cannot appear in a parameter.
     *
     * @param GeneratedValue<mixed> $element
     * @return GeneratedValue<T>
     */
    public function shrink(GeneratedValue $element);
}
