name: CI

on: [pull_request]

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php }}, dependencies ${{ matrix.dependencies }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.4, 8.0]
        dependencies:
          - "lowest"
          - "highest"
        include:
          - { php: 8.1, dependencies: "highest" }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: Run tests
        run: vendor/bin/phpunit test

  phpunit-compatibility:
    name: Test End to End with php ${{ matrix.php }}, phpunit ${{ matrix.phpunit }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { phpunit: 9, php: 8.1 }
          - { phpunit: 9, php: 8.0 }
          - { phpunit: 8, php: 7.4 }
          - { phpunit: 7, php: 7.3 }
          - { phpunit: 6, php: 7.1 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install dependencies
        uses: ramsey/composer-install@v1
      - name: Download phpunit phar
        run: |
          wget -O phpunit https://phar.phpunit.de/phpunit-${{ matrix.phpunit }}.phar
          chmod +x phpunit
      - name: Run tests
        run: ./phpunit --testsuite EndToEnd
